general:
  bonusDuration: 600
  mapCycleDuration: 600
  defaultGameRules:
    - 'announceAdvancements:false'
    - 'showDeathMessages:false'
    - 'doInsomnia:false'
    - 'doDaylightCycle:false'
    - 'doWeatherCycle:false'
    - 'doMobSpawning:false'
    - 'doTraderSpawning:false'
    - 'fallDamage:false'
    - 'mobGriefing:false'
    - 'doImmediateRespawn:true'
    - 'disableRaids:true'
    - 'keepInventory:true' # to prevent drops
bossbar:
  enabled: true
  text: '%map% &7(%expiry%)'
  color: 'YELLOW'
  style: 'SOLID'
killCommands:
  - 'say %attacker% killed %victim%'
items:
  trampoline:
    material: 'light_weighted_pressure_plate'
    displayName: '&6Trampoline'
    lore:
    - '&fLaunches you up: &7Right click'
messages:
  prefix: '&7[&eBFFA&7]'
  reload: '%prefix% &aConfiguration files successfully reloaded!'
  getItem: '%prefix% &aSuccessfully gave %amount%x &2%item% &ato player &2%player%.'
  bonusActivated: '%prefix% &2%bonus% &abonus activated for &2%seconds% &aseconds by &2%activator%.'
  bonusReset: '%prefix% &eAll active bonuses have been cleared.'
  noSuchPlayer: '%prefix% &cPlayer not found.'
  noSuchItem: '%prefix% &cItem not found.'
  mapChangeIncoming:
    seconds: '%prefix% &eMap change in &6%seconds% seconds&e.'
    minutes: '%prefix% &eMap change in &6%minutes% minutes&e.'
  mapChanged: '%prefix% &fMap changed to %map%&f.'
  setup:
    noSuchMap: '%prefix% &cNo map exists with this name.'
    alreadyExisting: '%prefix% &cThis world already exists as a map.'
    createError: '%prefix% &cThe specified world does not exist or is not loaded.'
    createSuccess: '%prefix% &aSuccessfully created a new map from world &2%world%.'
    displayNameSet: '%prefix% &2%map% &amap display name set to: &r%displayName%'
    spawnSet: '%prefix% &aSpawn point set for map &2%map%&a.'
    voidKillHeightSet: '%prefix% &aVoid kill height set to &2%y%&a.'
    voidKillHeightError: '%prefix% &cInvalid value provided.'
    deleted: '%prefix% &2%map% &amap permanently deleted.'
    deleteError: '%prefix% &cCannot delete map while it is in use.'
    defaultKitSaved: '%prefix% &aDefault kit saved successfully.'
  helpMenu:
    - '&e/%command% give <player> <item> <amount> &fGive special items'
    - '&e/%command% reload &fReload configuration files'
    - '&e/%command% skipmap &fSkip to next map (random)'
    - '&e/%command% setmap <map> &fSwitch to specific map'
    - '&e/%command% activatebonus <bonus_id> <activator_player> &fActivate bonus'
    - '&e/%command% resetbonuses &fClear all active bonuses'
  setupHelp:
    - '&e/%command% setup create <world> &fCreate new map'
    - '&e/%command% setup delete <map> &fDelete map'
    - '&e/%command% setup setdisplayname <map> <displayname> &fSet display name'
    - '&e/%command% setup setspawn <map> &fSet spawn point'
    - '&e/%command% setup setvoidkillheight <map> <y> &fSet void kill height'
    - '&e/%command% setup savedefaultkit &fSet default kit'